#ifndef PACKET_DEFS_H
#define PACKET_DEFS_H

#define TCP_VERSION 0x01
#define ADMIN_PACKET_HELLO_TYPE 0x11
#define ADMIN_PACKET_TYPE_PING 0x12
#define ADMIN_PACKET_TYPE_COMMAND 0x13
#define ADMIN_PACKET_TYPE_REPLY 0x14
#define ADMIN_PACKET_TYPE_KEEP_ALIVE 0xAAA

#endif
