#ifndef DEFINE_H
#define DEFINE_H

#define TCP_VERSION 0x01
#define BOT_PACKET_HELLO_TYPE 0x01
#define BOT_PACKET_TYPE_REPLY 0x02
#define BOT_PACKET_TYPE_COMMAND 0x03
#define BOT_PACKET_TYPE_KEEP_ALIVE 0xAA

#endif
